### ISSUE TITLE
Broken since October 2018

### ISSUE THREAD

**Issue by Beed28** [LenAnderson/YouTube-Mouseover-Preview#1]
YouTube seems to have updated sometime during October 2018; causing this script's mouseover previews to break and no longer load. They all just get stuck on "Loading Storyboard...", now.

The "No Storyboard. :(" message still works for streams that haven't aired yet, though.

**Comment by LenAnderson** [comment]
I know :(

But I'm surprised it took so long for them to break the script. YouTube used to change much faster than this...

I hope I'll find the time to investigate the changes sometime soon.

**Comment by LenAnderson** [comment]
Fixed :)
