### ISSUE TITLE
[Suggestion] Twitch Compatibility?

### ISSUE THREAD

**Issue by iiiGerardoiii** [LenAnderson/YouTube-Mouseover-Preview#6]
First of all thank you very much for making this script! It's super handy, specially with that Shift shortcut.

I was wondering if Twitch run their thumbnails in a similar way as Youtube's "Storyboard". Maybe adding such compatibility is a few lines of code away?

**Comment by LenAnderson** [comment]
Sorry, I don't use Twitch at all. Adding another site to this script would require pretty much a rewrite of most of the script. Plus keeping up with changes to the site as well.

Besides, I had a quick look and it seems that Twitch does not even have preview images when hovering over a video's timeline / progress bar, so something like YouTube's storyboard may not even exist on Twitch.
