### ISSUE TITLE
Hey there..Your script stopped working after the recent new update from YouTube

### ISSUE THREAD

**Issue by rakitanc** [LenAnderson/YouTube-Mouseover-Preview#9]
Please fix it. It would mean a lot

This is the behavior it's showing

https://user-images.githubusercontent.com/64612555/200874291-cdf8cd9c-c56f-4179-a802-d32df548a1b8.mp4

**Comment by LenAnderson** [comment]
Still works fine for me. So there's nothing I can do at the moment.

Where do the "1080p" in the upper left corner of the thumbnail and the little play button at the bottom of the thumbnail come from? Do you have other extensions or userscripts running? These may interfere with this script.  
I would check if it works without anything else affecting YouTube.

**Comment by karinaardos** [comment]
And today it stopped working in my firefox browser

**Comment by LenAnderson** [comment]
I don't have any problems in either Firefox or Chrome. I guess whatever update they've made hasn't been rolled out to all users yet.

**Comment by rakitanc** [comment]
> Still works fine for me. So there's nothing I can do at the moment.
> 
> Where do the "1080p" in the upper left corner of the thumbnail and the little play button at the bottom of the thumbnail come from? Do you have other extensions or userscripts running? These may interfere with this script. I would check if it works without anything else affecting YouTube.

Checked with disabling other userscripts..Doesn't seem to fix it

Btw this is the script you were curious about
https://greasyfork.org/en/scripts/397094-youtube-video-preview-and-ratings-keyless

**Comment by LenAnderson** [comment]
Sorry, then we'll just have to wait until I get the same breaking update.

**Comment by igor17721** [comment]
Edge browser. It stopped working today just like in the video above.
Looking forward for a fix. 

Thanks!

**Comment by LenAnderson** [comment]
Good news, I guess... today YouTube finally started showing me the same behavior that is reported in this issue. So a fix is now on the way.

**Comment by rakitanc** [comment]
> Good news, I guess... today YouTube finally started showing me the same behavior that is reported in this issue. So a fix is now on the way.

Congrats Mate!! It's fixed on my end too. Kudos for all your efforts
